<?php
include("../controler/CommentControler.php");
include("connectdb.php");
?>
<?php
//处理从评论版传来的信息，并且将评论添加到数据库中
$conn=connectdb();
$id=$_POST['id'];
$name=$_POST['username'];
$email=$_POST['email'];
$comment=$_POST['comment'];
comment_add($conn,$id,$name,$comment,$email);
header("Location:../view/caogao.php?id={$id}");
mysql_close($conn);
?>